# Generated by Django 3.1.7 on 2021-04-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='username')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='register date')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
